import { AccountSearch } from "@/components";
import Head from "next/head";
import { Container, Text } from "@nextui-org/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container
          css={{ display: "flex", flexDirection: "column", gap: "$12" }}
        >
          <Text h1>Top Mastodon posts</Text>
          <Text>See a Mastodon account&rsquo;s most favo(u)rited posts</Text>
          <AccountSearch />
        </Container>
      </main>
    </>
  );
}
