import { AccountSearch } from "@/components";
import Head from "next/head";
import { Container } from "@nextui-org/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <h1>Top Mastodon posts</h1>
          <AccountSearch />
        </Container>
      </main>
    </>
  );
}
